[build]
builder = "NIXPACKS"
root = "backend"
buildCommand = "python -m pip install -r requirements.txt"

[deploy]
startCommand = "gunicorn app:app"
preDeployCommand = "flask init-db"
healthcheckPath = "/"
healthcheckTimeout = 120
